# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=arm
CONFIG_SOFTMMU=yes
TARGET_XML_FILES= /home/stella/PML-Xen10/tools/qemu-xen-traditional/gdb-xml/arm-core.xml /home/stella/PML-Xen10/tools/qemu-xen-traditional/gdb-xml/arm-vfp.xml /home/stella/PML-Xen10/tools/qemu-xen-traditional/gdb-xml/arm-vfp3.xml /home/stella/PML-Xen10/tools/qemu-xen-traditional/gdb-xml/arm-neon.xml
CONFIG_SOFTFLOAT=yes
