# Automatically generated by configure - do not modify
TARGET_I386=y
TARGET_NAME=i386
TARGET_BASE_ARCH=i386
TARGET_ABI_DIR=i386
CONFIG_XEN=y
CONFIG_XEN_PCI_PASSTHROUGH=y
CONFIG_SOFTMMU=y
TARGET_XML_FILES= /home/stella/PML-Xen10/tools/qemu-xen/gdb-xml/i386-32bit.xml /home/stella/PML-Xen10/tools/qemu-xen/gdb-xml/i386-32bit-core.xml /home/stella/PML-Xen10/tools/qemu-xen/gdb-xml/i386-32bit-sse.xml
CONFIG_I386_DIS=y
CONFIG_I386_DIS=y
LDFLAGS+=
QEMU_CFLAGS+=
